// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgvqyvyzevkzrvsmaukn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxndnF5dnl6ZXZrenJ2c21hdWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzYyNTEsImV4cCI6MjA2MDg1MjI1MX0.mMnHJ38ivf2lGhNWzXGxNHy1-mqsa6Q59wkiS42SkxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);